name: Deploy to Somee via FTP

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Upload to Somee FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST_FTP }}
          username: ${{ secrets.USER_FTP }}
          password: ${{ secrets.PASSWORD_FTP }}

          protocol: ftp
          security: loose

          local-dir: ./public/
          server-dir: /   # Sử dụng "/" nếu đó là thư mục gốc, hoặc "www.dh52201516.somee.com"

          exclude: |
            **/.git/**
            **/.github/**
            **/*.yml
            **/node_modules/**
            **/bin/**
            **/obj/**
            .gitignore
            .gitattributes
